name: x_router
description: Navigator 2.0 made simple
version: 0.0.1
homepage: https://github.com/cedvdb/x_router

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

