name: x_router
description: A simple and powerful routing lib that simplify having multiple child router.
version: 0.2.0
homepage: https://github.com/cedvdb/x_router

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
